
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cim.zerocloud.io
  resources:
  - mirrorconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cim.zerocloud.io
  resources:
  - mirrorconfigs/status
  verbs:
  - get
  - patch
  - update
