# permissions for end users to view mirrorconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: viewer
rules:
- apiGroups:
  - cim.zerocloud.io
  resources:
  - mirrorconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cim.zerocloud.io
  resources:
  - mirrorconfigs/status
  verbs:
  - get
