name: ci

on:
  push:
    branches: [ master ]
    paths: [".github/workflows/ci.yml", "Dockerfile", "go.mod", "go.sum", "main.go", "api/**", "controllers/**", "pkg/**", "test/**"]
  pull_request:
    branches: [ master ]
    paths: [".github/workflows/ci.yml", "Dockerfile", "go.mod", "go.sum", "main.go", "api/**", "controllers/**", "pkg/**", "test/**"]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout git repository"
        uses: actions/checkout@v2

      - name: "Go build (using docker"
        run: docker build -t ghcr.io/danielsel/cim:latest --cache-from ghcr.io/danielsel/cim:latest --build-arg BUILDKIT_INLINE_CACHE=1 . 
        env:
          NODE_OPTIONS: "--max_old_space_size=7168"
          DOCKER_BUILDKIT: 1

      - name: "Push to GitHub Container Registry (GHCR)"
        if: github.event_name == 'push'
        run: |
          echo $PAT | docker login ghcr.io --username danielsel --password-stdin
          docker push ghcr.io/danielsel/cim:latest
          rm ~/.docker/config.json
        env:
          PAT: ${{ secrets.PAT }}
